server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，职责就是维服务实例，并不需要取检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #            http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka #.com:7002/eureka/
